version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    env_file: ./mariadb.env
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume:
          nocopy: true

  app:
    image: 15cm/ampache-apache-docker
    depends_on:
      - db
    restart: always
    env_file: ./ampache.env
    networks:
      - default
      - g_proxy
    volumes:
      - type: volume
        source: app-data
        target: /media
        volume:
          read-only: true
          nocopy: true
      - type: volume
        source: app-config
        target: /var/www/html/config
        volume:
          nocopy: true
    ports:
      - "8080:80"

volumes:
  db-data:
  app-data:
  app-config:
